// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconFaSolid:ellipsisV': typeof import('~icons/fa-solid/ellipsis-v')['default']
    'IconLa:language': typeof import('~icons/la/language')['default']
    'IconLa:spinner': typeof import('~icons/la/spinner')['default']
    'IconMaterialSymbols:checkCircleRounded': typeof import('~icons/material-symbols/check-circle-rounded')['default']
    'IconPh:caretDownBold': typeof import('~icons/ph/caret-down-bold')['default']
    'IconPrime:externalLink': typeof import('~icons/prime/external-link')['default']
    'IconPrime:timesCircle': typeof import('~icons/prime/times-circle')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    'IconUis:timesCircle': typeof import('~icons/uis/times-circle')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
